#!/bin/sh

# Date and time
date=$(date +'%a, %d %B  | %I:%M %p')

# Battery percentage #
battery=$(cat /sys/class/power_supply/BAT0/capacity)%
bat_status=$(cat /sys/class/power_supply/BAT0/status)
if [[ $bat_status == "Discharging" ]]; then
    battery_icon="󰁹"
else
    battery_icon="󰂄"
fi

# Network state #

# networkctl output
output=$(networkctl status --no-pager)

# network state
net_state=$(printf '%s\n' "$output" | awk '/State:/ {print $2}')

case $net_state in
    routable) net_state="online" ;;
    *)        net_state="offline" ;;
esac

if [ "$net_state" = "offline" ]; then
    network="󰖪" 
fi

nif=$(printf '%s\n' "$output" | awk '/Address:/ {print $4}')
case $nif in
    wlan*)
        iw=$(iwctl station wlan0 show 2>/dev/null)
        ssid=$(printf '%s\n' "$iw" | sed -n 's/.*Connected network[[:space:]]\+//p' | xargs)
        network="$ssid 󰖩"
        ;;
    enp*)
        network="Ethernet online 󰈀"
        ;;
esac

# Bluetooth #
bluetooth_devices=$(bluetoothctl devices Connected 2>/dev/null | wc -l)

# Microphone
if wpctl get-volume @DEFAULT_AUDIO_SOURCE@ 2>/dev/null | grep -q "MUTED"; then
    micro=" "
else
    micro=""
fi

# Speaker
if wpctl get-volume @DEFAULT_AUDIO_SINK@ 2>/dev/null | grep -q "MUTED"; then
    speaker="󰖁"
else 
    speaker="󰕾"
fi

# Keyboard Layout
layout="$(swaymsg -t get_inputs -r | jq -r '.[].xkb_active_layout_name // empty' | head -1)  "

echo "$layout | $speaker | $micro | $bluetooth_devices  | $network | $battery $battery_icon | $date  "
