#!/bin/sh

set -euo pipefail

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

mkdir -vp \
    ~/.config \
    ~/.local \
    "$DATA_HOME" \

[[ -d ~/.local/bin ]] && [[ ! -L ~/.local/bin ]] && mv ~/.local/bin/ ~/.local/bin-backup && echo 'Old ~/.local/bin dir backedup!'

stow -v \
  alacritty \
  lf \
  nvim \
  picnic \
  python \
  scripts \
  tmux \
  urlview \
  vivid \
  wget \
  zathura \
  zshell

echo 'done!'
