#!/bin/sh

set -euo pipefail

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

# We don't want to symlik these
mkdir -vp \
    ~/.config \
    ~/.local \
    ~/.librewolf \
    "$DATA_HOME" \
    "$CONFIG_HOME/systemd/user/" \
    ~/.config/borg
    

# I want the ~/.local/bin dir to be symlinked to my scripts
[[ -d ~/.local/bin ]] && [[ ! -L ~/.local/bin ]] && mv ~/.local/bin/ ~/.local/bin-backup

stow -v \
  alacritty \
  applications \
  bkgs \
  borg \
  direnv \
  dunst \
  exiftool \
  fonts \
  gammastep \
  handlr \
  lf \
  librewolf \
  mamba \
  nvim \
  personal \
  python \
  R \
  scripts \
  shell \
  sway \
  swaynag \
  systemd \
  tmux \
  tofi \
  vivid \
  wget \
  xdg-user-dirs \
  zathura

echo 'done!'
