#!/bin/sh
case $1 in
    period-changed)
        case $3 in 
            daytime)
                emoji=
                ;;
            transition)
                emoji=󰤖
                ;;
            night)
                emoji=
                ;;
            *)
                emoji=""
        esac
        exec dunstify "Gammastep" "Period changed to $3 $emoji"
esac
