#!/bin/bash

# Date and time
date=$(date +'%a, %d %B  | %I:%M %p')

# Battery percentage
battery=$(cat /sys/class/power_supply/BAT0/capacity)%
status=$(cat /sys/class/power_supply/BAT0/status)
if [[ $status == "Discharging" ]]; then
    battery_icon="󰁹"
else
    battery_icon="󰂄"
fi

# WiFi
network="$(network_state)"

# Bluetooth
bluetooth_devices=$(bluetoothctl devices Connected 2>/dev/null | wc -l)

# Microphone
if wpctl get-volume @DEFAULT_AUDIO_SOURCE@ 2>/dev/null | grep -q "MUTED"; then
    micro=" "
else
    micro=""
fi

# Speaker
if wpctl get-volume @DEFAULT_AUDIO_SINK@ 2>/dev/null | grep -q "MUTED"; then
    speaker="󰖁"
else 
    speaker="󰕾"
fi

echo "$speaker | $micro | $bluetooth_devices  | $network | $battery $battery_icon | $date  "
